name: Press Notification

on:
  push:
    paths:
      - "**/press.html"
      - "**/press.xml"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord notification
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds":[{
              "title":"New Press Release â€” Moeezland",
              "description":"A new official announcement has been published.",
              "url":"https://moeezland.com/press.html",
              "footer":{"text":"Government of Moeezland"}
            }]
          }' \
          ${{ secrets.https://discord.com/api/webhooks/1462126190180565154/Vb3RCwWT6j88KsNTiUhXKUkximYKHYhqcIhK48T4H3pb0YLf_YMPX-kUDycCQWPrexNn }}
